# -*- coding: utf-8 -*-
"""One-off content update for src/lib/law-data.json from the Winter/September 2026
exam companion docx (FOUNDATIONS OF LAW.docx dump).

- Repairs concept strings that were truncated with "..." using the doc's full text.
- Merges in new/richer Part C content as additional key_concepts.
- Adds new exam Q&As (Q34+) mined from Parts B/D, attached to matching topics.
- Adds topic 15 (Exam-day briefing & lecturer flags).

Existing topic nums/titles and existing qnums are NEVER changed (study progress is
keyed by qnum in localStorage).
"""
import json
import sys

PATH = "src/lib/law-data.json"

EMD = "\u2014"  # —
LSQ, RSQ = "\u2018", "\u2019"  # ' '
LDQ, RDQ = "\u201c", "\u201d"  # " "


def sq(s):  # curly single quotes around s
    return LSQ + s + RSQ


def dq(s):  # curly double quotes around s
    return LDQ + s + RDQ


# ---------------------------------------------------------------------------
# 1. Repairs: (topic_num, concept_index) -> (prefix_of_old, full_new_text)
# ---------------------------------------------------------------------------
REPAIRS = {
    (1, 0): ("Law vs policy vs opinion.",
             "Law vs policy vs opinion. Law is binding, enforceable by courts, and backed by sanctions; policy is government direction/principle guiding decision-making (not itself enforceable); opinion is a personal view with no binding force. Law derives from recognised sources (Parliament; courts); policy and opinion do not."),
    (1, 3): ("Legislation (statute law)",
             "Legislation (statute law) " + EMD + " Acts of Parliament and delegated/subordinate legislation (regulations, rules, by-laws made by the executive under delegated authority); became dominant in the 20th" + EMD.replace(EMD, "\u2013") + "21st centuries with increased regulation. Legislation takes precedence over case law where the two conflict (a valid statute overrides inconsistent common law " + EMD + " e.g. Civil Liability Act 2002 (NSW) s 71 overriding Cattanach v Melchior)."),
    (1, 4): ("Rule of law.",
             "Rule of law. Core contentions (Diceyan tradition): supremacy of regular law over arbitrary power; equality before the law (no one is above the law, including government); law is prospective, clear, stable; access to independent courts; judicial independence protects it. Contemporary formulations add government under law, legality, certainty, procedural fairness and access to justice. Linked exam angles: judicial independence; Magna Carta" + RSQ + "s " + dq("lawful judgment of peers or the law of the land") + "; habeas corpus."),
    (2, 0): ("Definitions of law",
             "Definitions of law (know 2" + "\u2013" + "3): Hart " + EMD + " " + dq("a system of rules") + " (The Concept of Law); Austin " + EMD + " " + dq("the command of a sovereign backed by sanction") + "; Dworkin " + EMD + " an interpretive concept aimed at justice; Raz " + EMD + " an authority mediating interests; Holmes " + EMD + " " + dq("prophecies of what the courts will do in fact, and nothing more pretentious") + "; Aquinas " + EMD + " rational ordering aimed at the common good, promulgated by those in charge of the community."),
    (2, 3): ("Case study",
             "Case study " + EMD + " The Case of the Speluncean Explorers (Fuller, 1949): fictional cave-in survivors kill and eat one companion; convicted of murder. Five judges map onto the schools: Truepenny CJ (strict application + clemency " + EMD + " positivist/formalist); Foster J (law of nature; the explorers were " + dq("outside") + " the law" + RSQ + "s jurisdiction " + EMD + " natural law); Tatting J (emotionally conflicted, withdraws); Keen J (strict fidelity to the statute; keep morality out " + EMD + " positivism); Handy J (pragmatic; public opinion matters " + EMD + " realism). Use it to show how jurisprudential commitments drive outcomes."),
    (2, 4): ("Companion case",
             "Companion case " + EMD + " R v Dudley and Stephens (1884) 14 QBD 273: shipwrecked sailors killed the cabin boy Richard Parker to survive; necessity is no defence to murder; deliberate killing of an innocent cannot be justified even in extremity (contrast Foster J" + RSQ + "s reasoning in Speluncean)."),
    (2, 5): ("Judicial methods",
             "Judicial methods (Kiefel CJ, " + sq("Judicial Methods in the 21st Century") + ", 2017 " + EMD + " prescribed reading): modern High Court practice " + EMD + " comprehensive written submissions since 1997; pre- and post-hearing conferences; first-draft allocation to avoid unnecessary judgments; prompt delivery. Useful for " + dq("role of judges") + " questions (March 2026 Q1)."),
    (3, 0): ("Why it matters",
             "Why it matters: Gummow " + EMD + " lawyers lack " + dq("deep appreciation of the techniques of statutory analysis") + "; Kirby " + EMD + " " + dq("the construction of statutes is now, probably, the single most important aspect of legal and judicial work\u2026 Where statute speaks\u2026 there is no escaping the duty to give meaning to its words.") + " Lord Steyn: interpretation is an art, involving choices between feasible interpretations. Spigelman CJ: fashion has moved " + dq("from text to context") + "."),
    (3, 3): ("\u201cThe starting point",
             dq("The starting point\u2026 is the text\u2026 whilst, at the same time, regard is had to its context and purpose. Context should be regarded at this first stage and not at some later stage and it should be regarded in its widest sense") + ": SZTAL v Minister for Immigration and Border Protection [2017] HCA 34 at [14] (Kiefel CJ, Nettle and Gordon JJ). Gageler J at [37]" + "\u2013" + "[39]: the task " + dq("begins, as it ends, with the statutory text") + "; the choice between potential meanings turns on the relative coherence of the alternatives with the statute" + RSQ + "s objects or policies."),
    (3, 4): ("CIC Insurance",
             "CIC Insurance Ltd v Bankstown Football Club Ltd (1997) 187 CLR 384 at 408: the modern approach (a) insists context be considered in the first instance, not merely when ambiguity arises, and (b) uses " + sq("context") + " in its widest sense " + EMD + " the existing state of the law and the mischief the statute was intended to remedy (including law reform reports)."),
    (3, 5): ("Pull-back to text",
             "Pull-back to text (" + dq("full circle") + "): Chevron Australia Holdings v FCT [2017] FCAFC 62 (Allsop CJ) " + EMD + " beginning and ending with the words " + dq("is not a call to narrow textualism\u2026 Context, however, is indispensable") + "; FCT v Consolidated Media Holdings [2012] HCA 55 " + EMD + " extrinsic materials cannot displace the meaning of the statutory text; Certain Lloyd" + RSQ + "s Underwriters v Cross [2012] HCA 56 " + EMD + " " + dq("the purpose of a statute resides in its text and structure") + "; Project Blue Sky v ABA (1998) 194 CLR 355 " + EMD + " the legal meaning may depart from the grammatical meaning where context, purpose or the canons so indicate."),
    (3, 7): ("Literal rule",
             "Literal rule " + EMD + " apply the ordinary/natural meaning even if inconvenient: Amalgamated Society of Engineers v Adelaide Steamship Co Ltd (1920) 28 CLR 129 per Higgins J at 161" + "\u2013" + "2 (" + dq("it is our duty to obey that meaning, even if we think the result to be inconvenient or impolitic or improbable") + "); Higgon v O" + RSQ + "Dea [1962] WAR 140."),
    (3, 9): ("Mischief rule",
             "Mischief rule (purposive ancestor) " + EMD + " Heydon" + RSQ + "s Case (1584) 3 Co Rep 7a: (1) the common law before the Act; (2) the mischief not provided for; (3) the remedy Parliament resolved; (4) construe to suppress the mischief and advance the remedy."),
    (3, 11): ("s 15AA",
             "s 15AA Acts Interpretation Act 1901 (Cth): the interpretation that would best achieve the purpose or object of the Act (whether or not expressly stated) is to be preferred to each other interpretation. Equivalent: s 33 Interpretation Act 1987 (NSW). Mills v Meeking (1990) 169 CLR 214 " + EMD + " no ambiguity is required before considering purpose, but the court " + dq("construes, not rewrites") + "."),
    (5, 2): ("Find legislation",
             "Find legislation: Federal Register of Legislation (legislation.gov.au) for Cth; NSW Legislation (legislation.nsw.gov.au); use point-in-time versions where the relevant date matters; check commencement provisions; Notes/penalty units."),
    (5, 3): ("Find cases",
             "Find cases: with a citation \u2192 AustLII, BarNet Jade, Lexis+, Westlaw; without a citation \u2192 subject searching, digests and citators (CaseBase, FirstPoint, LawCite) to check subsequent treatment (followed/distinguished/overruled) and parallel citations."),
    (6, 0): ("Why reference",
             "Why reference: lets the reader find and evaluate sources; transmits knowledge accurately; demonstrates grasp of materials; avoids plagiarism. Plagiarism consequences are severe " + EMD + " Re Liveri [2006] QCA 152 (admission as a legal practitioner refused where the applicant had submitted others" + RSQ + " work without attribution)."),
    (6, 3): ("Cases:",
             "Cases: Case Name (Year) Volume Report Series Page " + EMD + " italics; square brackets [year] where the year is the volume identifier; medium neutral: Case Name [Year] Court Number [pinpoint], e.g. Re Culleton [2017] HCA 3 [38]" + "\u2013" + "[43]. Cite the authorised report where available."),
    (8, 0): ("First Peoples",
             "First Peoples" + RSQ + " law before 1788: 65,000+ years of legal systems; 250+ language groups with defined territories; law embedded in the Dreaming; songlines as oral legal maps; elders administering restorative justice (reconciliation, compensation, ceremony rather than punishment); sophisticated land management (fire-stick farming, aquaculture " + EMD + " Gunditjmara fish traps at Lake Condah); diplomacy and trade networks. Contradicts the colonial portrayal used to justify settlement."),
    (8, 1): ("Colonisation and terra nullius",
             "Colonisation and terra nullius: Cook (1770) claimed the east coast as New South Wales; loss of the American colonies (1783) and the penal crisis drove the First Fleet (arrived January 1788; colony proclaimed 7 February 1788). Under Blackstone" + RSQ + "s scheme, territory could be acquired by conquest, cession or settlement; Australia was treated as settled because it was " + dq("practically unoccupied, without settled inhabitants or settled law") + " " + EMD + " the doctrine of terra nullius. Confirmed in Cooper v Stuart (1889) 14 App Cas 286 (PC)."),
    (8, 2): ("Reception of English law",
             "Reception of English law: received on settlement and formalised by the Australian Courts Act 1828 (Imp) " + EMD + " reception date 25 July 1828 for NSW (and later Qld/Vic); WA 1 June 1829; SA 28 December 1836; ACT/NT 1 January 1911. English law applied so far as suitable to colonial conditions (SGIC v Trigwell (1979) 142 CLR 617); see also the Imperial Acts Application Act 1969 (NSW)."),
    (8, 3): ("Jurisdiction over Indigenous peoples",
             "Jurisdiction over Indigenous peoples (erosion of autonomy): R v Ballard (1829) " + EMD + " early reluctance to apply English law to intra-Indigenous disputes; R v Murrell (1836) " + EMD + " asserted universal jurisdiction; denied Indigenous sovereignty; R v Bonjon (1841) " + EMD + " lingering ambiguity. Protection regimes \u2192 confinement on reserves, Stolen Generations \u2192 modern over-representation in the criminal justice system (post-RCIADIC responses include circle sentencing from 1999)."),
    (8, 10): ("Brennan J",
             "Brennan J at 39: " + LDQ + "The facts as we know them today do not fit the " + LSQ + "absence of law" + RSQ + " or " + LSQ + "barbarian" + RSQ + " theory\u2026 there is no warrant for applying in these times rules of the English common law which were the product of that theory." + RDQ),
    (9, 0): ("Development of the common law",
             "Development of the common law: before 1066, law was local custom (Anglo-Saxon county/hundred courts). The Norman Conquest (1066) brought feudalism (all land held of the Crown " + EMD + " knight service, socage, serjeanty, frankalmoign) and centralisation. The curia regis (King" + RSQ + "s Court) and itinerant justices (eyre/assize) spread royal justice, standardising rules into a law common to all England " + EMD + " the foundation of stare decisis. Henry II (1154" + "\u2013" + "89): Assize of Clarendon 1166 (presentment juries), standardised writs, expansion of royal courts."),
    (9, 1): ("The three common law courts",
             "The three common law courts: Exchequer (revenue), Common Pleas (civil disputes between subjects, fixed at Westminster per Magna Carta), King" + RSQ + "s Bench (Crown/criminal matters and supervisory jurisdiction via prerogative writs)."),
    (9, 2): ("The writ system",
             "The writ system: a writ = formal written order in the King" + RSQ + "s name, issued by Chancery, each writ defining a cause of action (" + dq("no writ, no remedy") + "). The Provisions of Oxford (1258) restricted the issue of new writs \u2192 rigidity \u2192 deserving cases had no remedy \u2192 petitions to the King/Council \u2192 referred to the Chancellor \u2192 growth of equity in the Court of Chancery."),
    (9, 3): ("Magna Carta",
             "Magna Carta (1215; reissued 1216" + "\u2013" + "17, 1225; confirmed 1297): baronial check on King John; fixed courts at Westminster; due process (" + dq("except by the lawful judgment of his peers or the law of the land") + "); justice not sold, denied or delayed; foundation of habeas corpus (codified Habeas Corpus Act 1679). First statement that the king is subject to the law " + EMD + " a cornerstone of the rule of law."),
    (9, 4): ("Equity " + EMD + " nature and contribution",
             "Equity " + EMD + " nature and contribution: a supplementary, discretionary, conscience-based system correcting common law rigidity (Maitland: " + dq("Equity had come not to destroy the law, but to fulfil it") + "). Contributions: the trust; remedies " + EMD + " injunction, specific performance, rescission, rectification; informal procedure; protection of the vulnerable. Conflict: Earl of Oxford" + RSQ + "s Case (1615) " + EMD + " where common law and equity conflict, equity prevails."),
    (10, 0): ("The Constitution:",
              "The Constitution: drafted at conventions (1891, 1897" + "\u2013" + "98); approved by colonial referenda; enacted as s 9 of the Commonwealth of Australia Constitution Act 1900 (UK) (Royal Assent 9 July 1900); in force 1 January 1901. It is the " + dq("birth certificate") + ": foundational rules binding Commonwealth and States; an Act contrary to it is invalid. Authority now rests on the sovereignty of the Australian people."),
    (10, 5): ("\u201cWashminster",
              dq("Washminster") + ": legislative and executive are fused in practice (Westminster responsible government " + EMD + " ministers sit in Parliament); the judiciary is strictly separated (federal influence " + EMD + " Boilermakers). Parliament delegates law-making to the executive (delegated legislation) subject to disallowance by either House."),
    (10, 6): ("The Crown and Governor-General",
              "The Crown and Governor-General: constitutional monarchy; the King acts on ministerial advice (s 2 appoints the G-G on the PM" + RSQ + "s advice). Reserve powers (exceptional, convention-governed): appoint/dismiss a PM; refuse/grant a dissolution. 1975 dismissal: G-G Sir John Kerr dismissed PM Whitlam after the Senate blocked supply " + EMD + " arguments both ways; illustrates the ambiguity of reserve powers and the role of constitutional conventions."),
    (10, 8): ("Commonwealth Parliament:",
              "Commonwealth Parliament: Senate " + EMD + " 12 per State + 2 each ACT/NT = 76 (equal State representation); House of Representatives " + EMD + " population-based, as near as practicable twice the Senate (the " + dq("nexus") + ", s 24); each original State \u2265 5 seats. Bills must pass both Houses and receive assent (s 58); Senate co-equal except s 53 (money bills); deadlocks \u2192 s 57 double dissolution and joint sitting."),
    (10, 10): ("s 51 " + EMD,
               "s 51 " + EMD + " enumerated (concurrent) heads of Cth power: trade and commerce (i), taxation (ii), defence (xxxi/xxxii), external affairs (xxix), corporations (xx), marriage (xxi), immigration (xxvii), industrial arbitration (xxxv), races (xxvi), acquisition of property on just terms (xxxi), referrals (xxxvii)."),
    (11, 0): ("Derivation of Australian law",
              "Derivation of Australian law from England: Blackstone" + RSQ + "s three modes " + EMD + " conquest, cession, settlement. Australia treated as settled (Cooper v Stuart (1889) 14 App Cas 286): settlers brought so much English law as was applicable to their new situation. Reception formalised by the Australian Courts Act 1828 (Imp) (reception date 25 July 1828 for NSW); extent of reception tested by suitability (Trigwell (1979)); Imperial legislation later tidied up by the Imperial Acts Application Act 1969 (NSW)."),
    (12, 0): ("NSW Constitution:",
              "NSW Constitution: principal source now the Constitution Act 1902 (NSW) (consolidating the 1855 (Imp) Act tradition). Unlike the Commonwealth" + RSQ + "s single entrenched document, it is flexible " + EMD + " mostly amendable by ordinary legislation (McCawley v The King (1920) 28 CLR 106), except manner-and-form entrenched provisions such as s 7A."),
    (12, 2): ("ss 3, 8A, 9A",
              "ss 3, 8A, 9A Constitution Act 1902 (NSW) + Australia Act 1986 (Imp) ss 7" + "\u2013" + "10: the Governor is the King" + RSQ + "s representative in NSW (s 9A; Australia Act s 7(1)); the Premier advises the King directly on State matters; no more UK oversight " + EMD + " Australia Act ss 8" + "\u2013" + "10 ended the reservation of State bills, UK legislative power and repugnancy invalidity."),
    (12, 3): ("Executive in practice:",
              "Executive in practice: Governor, Premier and Ministers; the Executive Council formalises Cabinet decisions (ss 35B" + "\u2013" + "35D); reserve powers and responsible-government conventions mirror the Commonwealth level (executive accountable to the Assembly)."),
    (12, 5): ("s 7 (constitution)",
              "s 7 (constitution), s 17 (election), s 22B(2): 42 members elected by state-wide proportional representation for eight-year staggered terms " + EMD + " half the Council faces election every four years at a general election. It is a continuing body " + EMD + " not subject to dissolution (stability/institutional memory)."),
    (12, 6): ("Manner-and-form entrenchment",
              "Manner-and-form entrenchment (CLVA 1865 tradition): s 7A " + EMD + " the Council cannot be abolished, and s 7A itself cannot be amended, without a referendum. Enforced in Attorney-General (NSW) v Trethowan [1932] AC 526 " + EMD + " a law passed in breach of a manner-and-form requirement is invalid; the CLVA 1865 supplied the authority for such self-entrenchment. Courts enforce compliance with manner-and-form requirements."),
    (12, 7): ("Clayton v Heffron",
              "Clayton v Heffron (1960) 105 CLR 214 " + EMD + " the s 7A referendum protects the Council even against the s 5B deadlock route: an abolition Bill must itself pass both Houses before going to the people, so the Assembly and Executive cannot use the deadlock machinery to bypass the Council."),
    (12, 9): ("s 24:",
              "s 24: four-year term running from the return of the writs. Fixed four-year terms introduced by the Constitution Amendment (Fixed Term Parliaments) Act 1995 (NSW); the Governor retains power to dissolve early (on advice); extending the term requires a referendum (s 7B)."),
    (13, 2): ("High Court of Australia",
              "High Court of Australia " + EMD + " apex; original jurisdiction ss 75 (mandamus/prohibition/injunction against Commonwealth officers " + EMD + " s 75(v); treaties; inter-State/Commonwealth disputes) and 76; appellate s 73 (from federal courts and State supreme courts " + EMD + " one common law: Lipohar). 7 Justices: High Court of Australia Act 1979 (Cth) s 6."),
    (13, 6): ("Cross-vesting limits",
              "Cross-vesting limits " + EMD + " Re Wakim; Ex parte McNally (1999) 198 CLR 511: the Commonwealth can invest State courts with federal jurisdiction, but the States cannot confer State jurisdiction on federal courts (Ch III forbids) " + EMD + " the cross-vesting scheme survives only in the State-to-federal direction."),
    (14, 0): ("The profession:",
              "The profession: fused-in-practice but functionally divided " + EMD + " solicitors (advise clients, prepare matters, may appear in lower courts) and barristers (specialist advocacy and advice; briefed by solicitors; the Bar). Admission via the Legal Profession Admission Board (LPAB) " + EMD + " academic (Priestley 11) + practical requirements (Legal Profession Uniform Admission Rules 2015, esp. r 10)."),
    (14, 1): ("Legal ethics",
              "Legal ethics " + EMD + " core obligations: honesty and candour to the court; competence and diligence; confidentiality/legal professional privilege; avoiding conflicts of interest; civility; no misleading conduct (Solicitors" + RSQ + " Conduct Rules 2015 rr 2" + "\u2013" + "6, 7" + "\u2013" + "12, 17, 19; Barristers Rules 2015 rr 4, 8, 11" + "\u2013" + "13, 17, 23). Character matters at admission and in practice " + EMD + " see the fitness and discipline cases (Clyne; Cummins; Re Liveri)."),
    (14, 2): ("AI and legal practice",
              "AI and legal practice (March 2026 Q3 theme): disruptive potential " + EMD + " drafting, research, prediction; risks " + EMD + " hallucinated citations filed with courts, confidentiality breaches via public tools, competence/verification and supervision duties, misleading the court. Lecturer" + RSQ + "s rule of thumb: using generative AI on client work needs (1) the client" + RSQ + "s consent and (2) your insurer" + RSQ + "s consent."),
}

# ---------------------------------------------------------------------------
# 2. Full replacements for non-truncated concepts (exact old text -> new text)
# ---------------------------------------------------------------------------
REWRITES = {
    (4, 11): ("Only the ratio decidendi (the decision on the material facts / ruling necessary to the decision) binds.",
              "Only the ratio decidendi (the decision on the material facts / ruling necessary to the decision) binds; obiter dicta are not binding but may be highly persuasive. Precedents are not abrogated by lapse of time " + EMD + " Pinnel" + RSQ + "s Case (1602) 5 Co Rep 117a is still cited."),
    (12, 11): ("Relationship between the NSW Houses " + EMD + " deadlock machinery:",
               "Relationship between the NSW Houses " + EMD + " deadlock machinery: ss 5A, 5B Constitution Act 1902 (NSW) set deadlock procedures where the Council rejects Assembly bills (joint sittings etc.); Clayton v Heffron protects the Council within that machinery; Taylor v Attorney-General (Qld) (1917) 23 CLR 457 on money bills and upper houses."),
}

print("definitions loaded ok")


# ---------------------------------------------------------------------------
# 3. New key_concepts appended per topic (merged from Part C / Week 12 lecture)
# ---------------------------------------------------------------------------
ADDITIONS = {
    1: [
        "Criminal vs civil law: criminal law is prosecuted by the Crown/state to punish and deter; burden " + EMD + " beyond reasonable doubt. Civil law resolves disputes between persons, aiming at compensation/remedy; burden " + EMD + " balance of probabilities. Also: substantive vs procedural law; domestic vs international law (public international law between states; private international law = conflict of laws).",
    ],
    3: [
        "Extrinsic materials " + EMD + " s 15AB Acts Interpretation Act 1901 (Cth) (\u2248 s 34 Interpretation Act 1987 (NSW)): explanatory memoranda, second reading speeches, committee reports, treaties and law reform reports may be used (a) to confirm the ordinary meaning, or (b) to determine the meaning where the provision is ambiguous or obscure or the ordinary meaning leads to absurdity/unreasonableness; weight assessed under s 15AB(2). Materials are tools, not substitutes " + EMD + " they cannot displace clear text (Goyal v West [2021] NSWSC 526 per Ward CJ in Eq at [63]ff sets out the working principles). At common law, headings are not used as an aid to interpretation.",
        "Maxims/canons of construction: noscitur a sociis (a word is known by its companions); ejusdem generis (general words following specific words are read down to the same class); expressio unius est exclusio alterius (expressing one thing excludes others); generalia specialibus non derogant (general provisions do not override specific ones). Servants of purpose, not rigid rules.",
        "Presumptions of interpretation (rebuttable by clear words): Parliament does not intend to abrogate fundamental common law rights (the principle of legality), abolish property rights without compensation, operate retrospectively, create offences without mens rea, oust the courts" + RSQ + " jurisdiction, or bind the Crown. Penal provisions are construed strictly in favour of the accused.",
        "Statutory vs constitutional interpretation: same textual-purposive techniques, but the Constitution is " + dq("broad and general in its terms, intended to apply to varying conditions") + " (Jumbunna Coal Mine (1908) 6 CLR 309 per O" + RSQ + "Connor J) " + EMD + " lean to the broader reading of Commonwealth powers; Engineers" + RSQ + " literalism applies to constitutional grants; precedent plays a weaker role because only a s 128 referendum can correct error.",
        "Exam problem-solving sequence: (1) read the provision" + RSQ + "s text; (2) read it in the context of the whole Act (definitions, structure, objects); (3) identify purpose from text/structure (s 15AA/s 33); (4) if ambiguity/absurdity, check extrinsic materials (s 15AB/s 34); (5) apply relevant maxims/presumptions; (6) state the construction and apply to the facts " + EMD + " citing SZTAL/CIC/Mills v Meeking as the framework.",
    ],
    4: [
        "One common law of Australia: Lipohar v R (1999) 200 CLR 485 " + EMD + " the High Court sits at the apex (s 73); there is a single Australian common law, not one per State. Intermediate appellate discipline: Farah Constructions (2007) 230 CLR 89 " + EMD + " intermediate courts should not depart from decisions of intermediate appellate courts in other jurisdictions on Commonwealth or uniform national law unless convinced they are plainly wrong.",
        "Overruling a court" + RSQ + "s own decisions " + EMD + " with caution: where the earlier decision is " + dq("manifestly wrong") + ", " + dq("clearly erroneous") + ", where strong reasons are shown, or maintenance is contrary to the public interest (Telstra v Treloar); departure should be rarer still for statutory construction. 2025 illustration: Stott v Commonwealth [2025] HCA 39 overruled University of Wollongong v Metwally (1984) as manifestly wrong on a question of constitutional importance.",
        "Finding the ratio: MacCormick (prescribed reading) " + EMD + " a ruling sufficient to settle a point of law put in issue by the parties and necessary to justify the decision; there can be multiple rationes (or no single ratio) in multi-judge courts. Goodhart fall-back " + EMD + " the material facts as the judge represented them plus the decision. Coleman v Power (2004) 220 CLR 1: " + dq("Cases are only authorities for what they decide") + "; Taylor v Rudaks (2007) 166 FCR 451 " + EMD + " a view expressed without full argument is not ratio. Distinguishing routes: materially different facts; statement too wide; mere obiter; wrongly decided; unsatisfactory reasoning; changed social conditions.",
        "Judicial law-making (March 2026 Q1 theme): the declaratory theory (" + dq("judges declare, not make law") + ") vs reality " + EMD + " Reid, " + sq("The Judge as Law Maker") + " (1972): belief in a complete pre-existing common law is a " + dq("fairytale") + ". Judges develop the law interstitially within the constitutional framework (Mabo (No 2) per Brennan J); Parliament may override (Cattanach v Melchior reversed in part by Civil Liability Act 2002 (NSW) s 71). Dissents " + EMD + " e.g. Kirby and Callinan JJ in WorkChoices " + EMD + " preserve alternative reasoning and drive later development.",
    ],
    8: [
        "Native Title Act 1993 (Cth) " + EMD + " enacted under the race power; s 223 defines native title (rights/interests in land or waters under traditional laws and customs, with continuing connection); validated past acts (curing inconsistency with the Racial Discrimination Act 1975 (Cth)); Federal Court determinations, NNTT mediation, future-act regime (good-faith negotiation), ILUAs. Upheld: Western Australia v Commonwealth (Native Title Act Case) (1995) 183 CLR 373.",
        "Wik Peoples v Queensland (1996) 187 CLR 1 " + EMD + " native title can coexist with pastoral leases; where inconsistent, the pastoralist" + RSQ + "s rights prevail. Howard Government" + RSQ + "s 10-Point Plan \u2192 Native Title Amendment Act 1998 (Cth). Fejo v Northern Territory (1998) 195 CLR 96 " + EMD + " freehold extinguishes native title permanently (no revival).",
        "Before and around Mabo: Milirrpum v Nabalco Pty Ltd (1970) 17 FLR 141 " + EMD + " communal native title not recognised (Gove land rights case) \u2192 prompted land rights legislation; Walker v New South Wales (1994) 182 CLR 45 " + EMD + " no parallel Indigenous criminal law; the criminal law applies universally. Also: Wurridjal v Commonwealth (2009) 237 CLR 309 (s 51(xxxi) just terms applied); Kruger v Commonwealth (1997) 190 CLR 1 (Stolen Generations implied-rights claims mostly rejected).",
        "RECENT HCA DEVELOPMENT " + EMD + " Commonwealth v Yunupingu [2025] HCA 6 (Gumatj Clan, Gove Peninsula): (1) the Territories power s 122 is subject to the s 51(xxxi) just-terms guarantee; (2) Commonwealth acts extinguishing native title between 1911 and 1978 were an " + dq("acquisition of property") + " within s 51(xxxi); (3) native title is not " + dq("inherently susceptible to defeasance") + " " + EMD + " the Commonwealth" + RSQ + "s " + dq("fragile rights") + " argument rejected. Compensation arises under the NTA; quantum remitted to the Federal Court (claim reported at ~$700m). Builds on Griffiths v Northern Territory (Timber Creek) (2019) 269 CLR 1. Significance: native title is property protected by the Constitution like any other title.",
        "Constitutional dimension: original s 51(xxvi) excluded " + dq("the Aboriginal race in any State") + "; s 127 excluded Indigenous people from the census " + EMD + " the 1967 referendum (90.77% Yes " + EMD + " the highest ever) removed both. Uluru Statement from the Heart (2017): Voice, Treaty, Truth (Makarrata). The 2023 Voice referendum was defeated (~60% No; no State majority). NSW Constitution s 2(2) acknowledges Aboriginal peoples as the First Peoples of NSW.",
    ],
    9: [
        "More maxims: equity regards as done that which ought to be done (specifically performable contract \u2192 buyer treated as equitable owner from exchange); equity is equality; equity acts in personam.",
        "Nineteenth-century reforms \u2192 Judicature Acts 1873" + "\u2013" + "75 (Eng) (lecturer: " + dq("write that down") + ") " + EMD + " merged the common law courts and Chancery into one Supreme Court of Judicature, with a single set of rules and law and equity administered concurrently in every court, equity prevailing on conflict. NSW equivalent (much later): Supreme Court Act 1970 (NSW), especially s 57.",
        "UK constitutionalism chain: Magna Carta \u2192 Reformation Parliament (Act in Restraint of Appeals 1533; Act of Supremacy 1534) \u2192 Civil War (1642" + "\u2013" + "51) \u2192 Glorious Revolution 1688 \u2192 Bill of Rights 1689 (no suspending/dispensing with laws; no taxation without Parliament; free elections and parliamentary speech) \u2192 Act of Settlement 1701 (Protestant succession; judicial tenure during good behaviour " + EMD + " judicial independence). Result: parliamentary sovereignty " + EMD + " courts cannot invalidate an Act (Pickin v British Railways Board [1974] AC 765); Parliament cannot bind its successors. Contrast Australia: the Commonwealth has only enumerated powers and the Constitution is supreme and entrenched (s 128).",
    ],
    10: [
        "Amendment " + EMD + " s 128 referendum: absolute majority of both Houses (or the G-G submits on deadlock) \u2192 referendum within 2" + "\u2013" + "6 months \u2192 double majority (national majority AND majority in a majority of States) \u2192 royal assent. Only 8 of 44+ referendums have succeeded.",
        "Centralising interpretation by the High Court: Engineers" + RSQ + " Case (1920) " + EMD + " abandoned " + dq("reserved State powers") + "/implied immunities; s 51 read by its plain literal meaning in context \u2192 federal expansion. First Uniform Tax Case (1942) " + EMD + " ss 51(ii) + 96 monopolised income tax \u2192 vertical fiscal imbalance. Tasmanian Dam (1983) " + EMD + " external affairs supports treaty-implementing legislation on otherwise-local matters. WorkChoices (2006) " + EMD + " corporations power supports national workplace regulation (Kirby and Callinan JJ dissenting on the federal balance).",
        "Other federalism provisions: s 92 free interstate trade " + EMD + " prohibits protectionist burdens (Cole v Whitfield (1988); Betfair (2008)); s 117 no discrimination on State residence (Street v Queensland Bar Association (1989)); s 96 tied grants " + EMD + " a huge practical lever; s 51(xxxvii) referrals (e.g. corporations); s 122 Territories power " + EMD + " broad but subject to s 51(xxxi) just terms (Commonwealth v Yunupingu [2025] HCA 6); territories" + RSQ + " self-government is fragile (Cth override of NT euthanasia laws).",
        "Rights protection " + EMD + " no Bill of Rights: express rights are sparse (s 51(xxxi) just terms; s 80 jury trial for indictable Cth offences; s 116 free exercise of religion; s 92; s 117). Implied: freedom of political communication (Lange; McCloy structured proportionality " + EMD + " burden? compatible with representative government? suitable, necessary, adequate in balance); voting cases Roach (2007) and Rowe (2010); Ch III separation-of-powers protections (Kable line for State courts).",
    ],
    11: [
        "Federation (1 January 1901): conventions \u2192 Commonwealth of Australia Constitution Act 1900 (Imp); six colonies became States; new federal division of powers; High Court created 1903 (s 71; Judiciary Act 1903 (Cth)).",
        "The independence chain (lecturer: " + dq("I" + RSQ + "ve said it 3 times " + EMD + " you must know it") + "): Balfour Declaration 1926 (dominions equal in status) \u2192 Statute of Westminster 1931 (UK) (repugnancy invalidity removed; UK laws only with dominion consent; adopted by Australia only in 1942, retrospective to 3 September 1939) \u2192 Privy Council (Limitation of Appeals) Act 1968 (Cth) and Privy Council (Appeals from the High Court) Act 1975 (Cth) \u2192 Australia Acts 1986 (Cth and UK): ended ALL appeals to the Privy Council (from State courts " + EMD + " the must-know point), terminated UK legislative power over Australia, and ended repugnancy restrictions and reservation of State bills; States gained full legislative power (including extraterritorial " + EMD + " Mobil Oil (2002)). The remaining UK link is the shared Crown.",
    ],
    12: [
        "NSW legislative power is plenary, not enumerated: s 5 Constitution Act 1902 (NSW) " + EMD + " laws " + dq("for the peace, welfare and good government of New South Wales") + ", words of the widest amplitude (Union Steamship Co of Australia Pty Ltd v King (1988) 166 CLR 1); extraterritorial competence confirmed by the Australia Acts 1986 (Mobil Oil (2002)). Constraints: the Commonwealth Constitution (ss 90, 92, 109, 114" + "\u2013" + "117) and Ch III (Kable). " + dq("Plenary power") + " is " + dq("a particular favourite of examiners the country over") + " " + EMD + " contrast the Commonwealth" + RSQ + "s enumerated heads.",
        "s 109 doctrine in full (updated Topic 12 slides " + EMD + " high-yield): confirms Commonwealth supremacy over concurrent powers; operates only where both laws are otherwise valid; " + dq("invalid") + " means inoperative, not void " + EMD + " the State law revives if the Commonwealth law is repealed (Carter v Egg and Egg Pulp Marketing Board (1942) 66 CLR 557 per Latham CJ). Tests of " + dq("real conflict") + ": (1) direct " + EMD + " impossibility of simultaneous obedience; (2) direct " + EMD + " one law alters, impairs or detracts from a right, privilege or immunity conferred by the other; (3) indirect " + EMD + " " + dq("cover the field") + " (Ex parte McLean (1930) 43 CLR 472; Viskauskas v Niland (1983) 153 CLR 280).",
        "Stott v Commonwealth [2025] HCA 39 (decided 15 October 2025) " + EMD + " the essential 2025 case: Vic/Qld foreign-owner land tax/duty surcharges were inconsistent with non-discrimination clauses in Australia" + RSQ + "s tax treaties (given domestic force by the International Tax Agreements Act 1953 (Cth)) " + EMD + " " + dq("an exemplar of the application of s 109") + ". The HCA unanimously upheld the Commonwealth" + RSQ + "s retrospective cure (Treasury Laws Amendment (Foreign Investment) Act 2024 (Cth)) and overruled Metwally as " + dq("manifestly wrong") + ". Takeaway: the Commonwealth can now retrospectively remove s 109 inconsistency and revive State laws.",
        "Executive government (Topic 13 lecture): s 61 vests executive power in the Crown, exercisable by the G-G, extending to the " + dq("execution and maintenance of this Constitution, and of the laws of the Commonwealth") + "; content includes the prerogatives appropriate to the Commonwealth" + RSQ + "s spheres (Davis (1988); Ruddock v Vadarlis (2001) " + EMD + " the Tampa case) and a nationhood dimension (AAP Case (1975)). Limits: Pape v FCT (2009) (national-crisis spending); Williams [2012] HCA 23 " + EMD + " no spending/contracting without statutory authority merely because s 51 would support a law; displacement by statute requires clear words (De Keyser" + RSQ + "s (1920)). Cabinet operates by convention (Peko-Wallsend); responsible government means an executive accountable to Parliament (ministerial responsibility, though weakened in modern practice).",
    ],
    13: [
        "What is a court / judicial power (Week 12 lecture): the label is irrelevant " + EMD + " the question is whether the body exercises judicial power (Lane v Morrison (2009) 239 CLR 230: the Australian Military Court, on fixed terms and inside the defence command structure, was invalid). Judicial power determines rights and liabilities conclusively and enforceably (Huddart Parker (1909); Totani (2010) per Kiefel J); it is coercive, in invitum " + EMD + " unlike consensual arbitral power, which creates new rights (Waterside Workers (1918); TCL Air (2013)). Independence and impartiality are essential to any body exercising judicial power (Gypsy Jokers (2008)). Characterisation is contextual " + EMD + " no exhaustive definition is possible (Precision Data (1991)).",
        "Boilermakers" + RSQ + " Case (R v Kirby; Ex parte Boilermakers" + RSQ + " Society (1956) 94 CLR 254) " + EMD + " strict separation at the federal level: a Ch III court cannot exercise non-judicial power, and non-judicial tribunals cannot exercise federal judicial power (the dual judicial/arbitral Arbitration Court was invalidly constituted; upheld by the Privy Council). Exceptions: persona designata functions (Hilton v Wells (1985)); administrative functions incidental to judicial functions (Harris v Caladine (1991)). Burns v Corbett (2018) 265 CLR 304 " + EMD + " a State tribunal (NCAT) cannot exercise federal judicial power (e.g. s 75(iv) diversity matters).",
        "Jurisdiction (Week 12): the authority of a court to hear and decide the matter before it (Harris v Caladine); when properly invoked, it must be exercised. Original vs appellate " + EMD + " appellate jurisdiction is a creature of statute; there is no common law right of appeal (e.g. Supreme Court Act 1970 (NSW) s 101). Supervisory jurisdiction: the Supreme Court keeps inferior courts, tribunals and decision-makers within lawful power (mandamus, prohibition, certiorari) and it cannot be excluded " + EMD + " Kirk (2010); jurisdictional errors vs errors within jurisdiction " + EMD + " Craig (1995); jurisdictional error reviewable despite finality clauses " + EMD + " Probuild (2018). Federal jurisdiction needs a justiciable " + dq("matter") + " " + EMD + " no advisory opinions; accrued/associated jurisdiction (s 32 FCA Act; Philip Morris) covers State-law claims sharing a " + dq("common substratum of facts") + " with the federal claim.",
        "Tribunals and administrative review: tribunals are not Ch III courts " + EMD + " they conduct merits review (the " + dq("correct and preferable") + " decision on the facts, law and policy; Drake (1979)) and cannot exercise judicial power (Boilermakers). Federal: the Administrative Review Tribunal (ART) replaced the AAT on 14 October 2024; National Native Title Tribunal. NSW: NCAT (from 2014 " + EMD + " consumer, tenancy, guardianship, administrative review). Judicial review is legality only: ADJR Act 1977 (Cth); Judiciary Act 1903 (Cth) s 39B; Constitution s 75(v) " + EMD + " entrenched, so removing it needs a s 128 referendum.",
        "ADR (March 2026 Q2(a) module): negotiation; mediation (a neutral facilitates " + EMD + " no imposed outcome); conciliation (neutral plays a more active advisory role); expert appraisal/determination; arbitration (determinative " + EMD + " binding award, confidential, much harder to challenge than a judgment; courts enforce arbitration clauses). Court-connected ADR is standard case management: a NSW court may refer proceedings to mediation without the parties" + RSQ + " consent (Civil Procedure Act 2005 (NSW) s 26; arbitration with consent, s 38; overriding purpose of just, quick and cheap resolution, s 56) " + EMD + " but it cannot force settlement; the right to an adjudicated outcome remains. Over 95% of civil matters settle. Debate: settlement pressure vs the judiciary" + RSQ + "s constitutional function of open, reasoned adjudication (Windeyer, prescribed reading).",
    ],
    14: [
        "Regulation: Legal Profession Uniform Law (NSW) " + EMD + " admission and practising certificates (ss 16, 17), trust accounts, conduct rules, discipline (s 419); Legal Profession Uniform Law Australian Solicitors" + RSQ + " Conduct Rules 2015; Legal Profession Uniform Conduct (Barristers) Rules 2015 " + EMD + " including the cab-rank rule: a barrister must accept a brief in their area of practice regardless of personal views about the client or cause, subject to exceptions such as conflict or inadequate fee.",
        "The " + dq("Grand Bargain") + ": in exchange for monopoly, status and self-regulation, the profession accepts duties to the court and the administration of justice paramount over the duty to the client, high ethical standards, and service to the public (Brennan, " + sq("Profession or Service Industry: The Choice") + " (1996)).",
        "Fitness and discipline cases (examinable list): Clyne v NSW Bar Association (1960) 104 CLR 186 (striking off; " + dq("suitable person") + " to remain on the roll); NSW Bar Association v Cummins (2001) 52 NSWLR 279 and Hamman [1999] NSWCA 404 (fit and proper person; candour with the regulator); re OG, a lawyer [2007] VSC 520 (conduct outside practice can still demonstrate unfitness); Re Liveri [2006] QCA 152 (law-school plagiarism \u2192 admission refused); Re Humzy-Hancock [2007] QSC 34 (academic misconduct and disclosure on admission).",
        "The judiciary: federal appointment, tenure and independence " + EMD + " s 72 Constitution (tenure/salary protection; removal only by address of both Houses); NSW " + EMD + " Judicial Officers Act 1986 (NSW) s 41 (removal only by address on proved misbehaviour/incapacity; complaints via the Conduct Division). Judicial independence underpins the rule of law " + EMD + " impartiality, security of tenure, freedom from executive interference, institutional integrity (Kable line).",
        "Judicial impartiality and bias (ALRC Report 138, Without Fear or Favour, December 2021): two rules " + EMD + " actual bias and apprehended bias; the apprehended-bias test is objective (Ebner v Official Trustee in Bankruptcy (2000) 205 CLR 337 at [6]): would a fair-minded lay observer reasonably apprehend that the judge might not bring an impartial mind to the question? Charisteas v Charisteas (2021) " + EMD + " undisclosed social contact between the trial judge and a party" + RSQ + "s barrister during the hearing \u2192 retrial ordered. ALRC: the substantive law needs no amendment, but procedures do (published disqualification protocols, an independent complaints body, transparent appointments).",
        "Judicial independence and the rule of law (March 2026 Q3(a)): independence safeguards impartial adjudication between citizen and state; threats " + EMD + " executive pressure, ad hominem legislation (Kable), funding, appointments processes, public attacks; safeguards " + EMD + " s 72 tenure, separation of powers, convention, professional culture. Engage critically: independence is instrumental, not an end " + EMD + " it serves impartial justice and public confidence.",
    ],
}


# ---------------------------------------------------------------------------
# 4. New questions (qnums continue the sequence; answers condensed from Part D)
# ---------------------------------------------------------------------------
NEW_QUESTIONS = {
    13: [
        {
            "qnum": "Q34",
            "question": "The (fictional) Building Justice Act 2026 (NSW) creates a Building Disputes Tribunal (BDT) to " + dq("finally and bindingly determine") + " building disputes, including between residents of different States; BDT members hold renewable three-year contracts and are removable by the Minister at will. The Act also empowers a NSW Supreme Court judge, acting in a personal capacity, to make building work prohibition orders without giving reasons. Meanwhile the (fictional) Defence Housing Act 2026 (Cth) creates a " + dq("Defence Housing Court") + " of serving ADF officers on fixed seven-year terms to make binding determinations of housing entitlements. Advise on the constitutional validity of each determination.",
            "answer": "Answer. The interstate dispute before the BDT is a matter " + dq("between residents of different States") + " within s 75(iv) " + EMD + " federal jurisdiction. The judicial power of the Commonwealth may be exercised only by Chapter III courts (s 71; Boilermakers), and a State tribunal that is not a court of a State cannot exercise it: Burns v Corbett (2018) 265 CLR 304 (NCAT). Determining disputes " + dq("finally and bindingly") + " is judicial power (Lane v Morrison at [21]" + "\u2013" + "[22]), and members on renewable contracts removable at ministerial will lack the independence and impartiality essential to a court (Gypsy Jokers at [10]) " + EMD + " the label cannot save it. The BDT therefore cannot validly determine the interstate dispute; it must go to a State or federal court. Purely intra-State matters may still be determined as an exercise of State administrative power.\n\nThe prohibition-order power is invalid under the Kable principle. State courts may be vested with non-judicial functions, but not functions incompatible with their institutional integrity as repositories of federal jurisdiction (Kable (1996); Forge v ASIC (2006)). Wainohu v NSW (2011) 243 CLR 181 is on all fours: control orders made by Supreme Court judges in a personal capacity, without reasons, were invalid " + EMD + " the public could not distinguish the judicial and non-judicial roles, and the absence of reasons struck at a hallmark of judicial power. The prohibition orders mirror Wainohu (reinforce with Condon v Pompano (2013) and Totani).\n\nThe Defence Housing Court is invalid. A body that determines rights and liabilities conclusively and bindingly exercises judicial power (Totani at [444] per Kiefel J), which at the federal level may be vested only in a Ch III court. Fixed seven-year terms, serving ADF officers and a command-structure location are precisely the defects that invalidated the Australian Military Court in Lane v Morrison (2009) 239 CLR 230. Calling the body a " + dq("court") + " makes no difference; the determination is of no effect.",
        },
        {
            "qnum": "Q38",
            "question": "What was the significance of R v Kirby; Ex parte Boilermakers" + RSQ + " Society of Australia (1956) 94 CLR 254?",
            "answer": "Answer. Boilermakers established the strict separation of judicial power at the federal level " + EMD + " the lecturer calls it one of the most significant Australian constitutional decisions. The Commonwealth Court of Conciliation and Arbitration combined arbitral functions (making new awards " + EMD + " non-judicial) with judicial functions (enforcing awards). The High Court held, and the Privy Council affirmed, that Chapter III means what it says: a court exercising the judicial power of the Commonwealth cannot also be vested with non-judicial power, and a body that is not a Ch III court cannot exercise federal judicial power. The dual body was therefore invalidly constituted.\n\nTwo qualifications keep the doctrine workable. Judges may perform non-judicial functions in their personal capacity (persona designata " + EMD + " Hilton v Wells (1985)), and administrative functions incidental to judicial functions are permitted (Harris v Caladine (1991)).\n\nBoilermakers also explains adjacent doctrine: federal tribunals such as the ART can conduct merits review precisely because they exercise no judicial power, and State tribunals cannot exercise federal judicial power at all (Burns v Corbett (2018)). At State level there is no strict separation (Gilbertson), but the Kable principle protects the institutional integrity of State courts as repositories of federal jurisdiction. In an exam, use Boilermakers as the anchor for any question on what makes a body a court, the content of judicial power, or the validity of hybrid tribunals.",
        },
        {
            "qnum": "Q39",
            "question": "Distinguish mediation, arbitration and conciliation, and explain the courts" + RSQ + " power to compel ADR in NSW.",
            "answer": "Answer. All three are ADR processes " + EMD + " consensual, confidential and party-controlled alternatives (or adjuncts) to adjudication " + EMD + " but the neutral" + RSQ + "s role differs. In mediation the neutral facilitates negotiation between the parties and imposes no outcome; settlement, if any, is the parties" + RSQ + " own and is embodied in an enforceable deed of settlement. In conciliation the neutral plays a more active, advisory role, suggesting possible terms of settlement. In arbitration the neutral hears evidence and argument and makes a binding determination " + EMD + " the closest process to adjudication, though consensual in origin; awards are confidential, enforceable, and much harder to challenge than a judgment, and courts will hold parties to arbitration clauses they agreed to.\n\nCourt-connected ADR is now standard case management. Under the Civil Procedure Act 2005 (NSW) a court may refer proceedings to mediation without the parties" + RSQ + " consent where it considers the circumstances appropriate (s 26), and to arbitration with consent (s 38); the overriding purpose of the just, quick and cheap resolution of disputes (s 56) informs those powers. Parties referred to mediation must participate in good faith " + EMD + " but the court cannot make them settle; the right to an adjudicated outcome always remains.\n\nThe framing point: ADR complements rather than replaces adjudication. Over 95% of civil matters settle, which serves access to justice, but courts remain essential for the authoritative, public declaration of rights (rule of law).",
        },
        {
            "qnum": "Q40",
            "question": "Distinguish merits review from judicial review, giving the principal avenues for each.",
            "answer": "Answer. Merits review asks whether the correct and preferable decision was made on the facts, the law and policy. The reviewer stands in the shoes of the original decision-maker and may substitute a new decision (Drake v Minister for Immigration and Ethnic Affairs (1979)). It is conducted by tribunals, not courts: externally by the Administrative Review Tribunal federally (the ART replaced the AAT on 14 October 2024) and NCAT in New South Wales, or internally within the agency. Watch the legislation at every step " + EMD + " internal-review prerequisites, strict time limits, and leave to proceed out of time.\n\nJudicial review asks a narrower question: was the decision lawful? The court examines legality, not merits " + EMD + " jurisdictional error, breach of procedural fairness, errors of law. Principal avenues: the Administrative Decisions (Judicial Review) Act 1977 (Cth) for most Commonwealth decisions; Judiciary Act 1903 (Cth) s 39B in the Federal Court; and Constitution s 75(v) in the High Court, which is entrenched " + EMD + " removing it would require a s 128 referendum. In NSW, judicial review operates mainly at common law through the Supreme Court" + RSQ + "s supervisory jurisdiction (mandamus, prohibition, certiorari), which the legislature cannot exclude: Kirk (2010); Craig (1995) distinguishes jurisdictional errors (reviewable) from errors within jurisdiction (generally not); Probuild (2018) confirms review survives legislative finality clauses.\n\nThe distinction matters because it allocates work between the branches: tribunals re-decide; courts police legal limits. The lecturer" + RSQ + "s warning: " + dq("you can" + RSQ + "t get out of law school without knowing what merits review is") + ".",
        },
    ],
    5: [
        {
            "qnum": "Q35",
            "question": "Locate the Graffiti Control Act 2008 (NSW) and read s 4(1). What are the elements of the offence, and what are penalty units?",
            "answer": "Answer. Section 4(1) of the Graffiti Control Act 2008 (NSW) provides that a person must not, (1) without reasonable excuse (proof of which lies on the person), (2) intentionally mark, (3) any premises or other property, (4) unless the person has first obtained the consent of the occupier or person in charge (occupied premises) or the owner or person in charge (unoccupied premises or other property). The maximum penalty is 4 penalty units. An aggravated version (s 4(2), (6) " + EMD + " using a graffiti implement, making a non-removable mark, or marking a place of worship) carries 20 penalty units or 12 months" + RSQ + " imprisonment. Chalk on public footpaths is exempt (s 4(5)).\n\nPenalty units are a standard monetary unit that lets fines be indexed without amending every Act. In NSW, one penalty unit is $110 (Crimes (Sentencing Procedure) Act 1999 (NSW) s 17), so the s 4(1) maximum fine is $440. At Commonwealth level the unit is set by s 4AA of the Crimes Act 1914 (Cth) and is indexed " + EMD + " always check the current value.\n\nThe research steps this exercise tests: find the current Act on legislation.nsw.gov.au, read the operative provision element by element (noting where the burden of proof lies), and follow the note to the penalty-unit definition in other legislation.",
        },
    ],
    4: [
        {
            "qnum": "Q36",
            "question": "Case-note Cohen v Sellar [1926] 1 KB 536: material facts, issue, ratio and obiter.",
            "answer": "Answer. Cohen v Sellar [1926] 1 KB 536 (McCardie J, King" + RSQ + "s Bench Division). Material facts: an engagement ring was given in contemplation of marriage; the engagement was broken; the jury found the man had refused to carry out the promise of marriage. Procedurally, the breach-of-promise action had been tried with a jury, and the defendant" + RSQ + "s County Court action to recover the ring was removed to the High Court and heard as a counterclaim " + EMD + " so this judgment concerned the man" + RSQ + "s claim for return of the ring.\n\nIssue: who is entitled to an engagement ring when an engagement ends " + EMD + " is it an absolute gift, or a gift conditional on the marriage taking place?\n\nRatio: an engagement ring is a conditional gift, given on the implied condition that the marriage take place. If the recipient breaks the engagement she must return it; if the donor, without legal justification, refuses to marry, he cannot recover it (applying Jacobs v Davis, and Lord Sumner in Bank Line v Capel " + EMD + " no reliance on self-induced frustration). On the facts, Miss Cohen retained the ring.\n\nObiter: if the engagement ends by mutual consent, the ring goes back; on the donor" + RSQ + "s death or legal disability it is returnable; if the marriage occurs the ring becomes the recipient" + RSQ + "s absolute property; and the jury" + RSQ + "s non-binding suggestion was disregarded.\n\nThe case is a neat study in separating ratio from obiter: only the conditional-gift rule and its no-self-induced-frustration qualification were necessary to the decision.",
        },
    ],
    12: [
        {
            "qnum": "Q37",
            "question": "What is the " + dq("cover the field") + " test of s 109 inconsistency, and how has it been applied " + EMD + " including the 2025 development?",
            "answer": "Answer. Cover the field is the indirect test of s 109 inconsistency. Section 109 provides that where a State law is inconsistent with a Commonwealth law, the Commonwealth law prevails and the State law is, to the extent of the inconsistency, inoperative " + EMD + " not void: if the Commonwealth law were repealed, the State law revives (Carter v Egg and Egg Pulp Marketing Board (1942) per Latham CJ). s 109 operates only where both laws are otherwise valid.\n\nDirect tests ask whether simultaneous obedience is impossible, or whether one law alters, impairs or detracts from a right conferred by the other. The indirect " + dq("cover the field") + " test asks instead whether the Commonwealth law evinces an intention to be a complete, exhaustive or exclusive statement of the law on the subject; if so, any State law on that subject is inconsistent, even though obedience to both is possible (Ex parte McLean (1930)). In Viskauskas v Niland (1983) the Racial Discrimination Act 1975 (Cth) occupied the field of racial discrimination, leaving the State Anti-Discrimination Act inoperative.\n\nUniversity of Wollongong v Metwally (1984) had held that Parliament could not retrospectively cure a s 109 inconsistency. Stott v Commonwealth [2025] HCA 39 " + EMD + " " + dq("an exemplar of the application of s 109") + " " + EMD + " overruled Metwally as " + dq("manifestly wrong") + ": State foreign-owner tax surcharges were inconsistent with non-discrimination clauses in Australia" + RSQ + "s tax treaties, and the High Court unanimously upheld the Commonwealth" + RSQ + "s retrospective validating Act. The Commonwealth can now remove s 109 inconsistency retrospectively and revive State laws.",
        },
    ],
    14: [
        {
            "qnum": "Q41",
            "question": "How does the cab-rank rule apply to barristers in NSW, and what limits exist?",
            "answer": "Answer. The cab-rank rule requires a barrister to accept a brief in their area of practice regardless of their personal views about the client or the cause. It is embodied in the Legal Profession Uniform Conduct (Barristers) Rules 2015 and reflects the structure of the divided profession: solicitors brief barristers, who supply specialist advocacy and advice at the Bar.\n\nThe rule serves the administration of justice in two ways. It guarantees that even unpopular clients and causes can obtain specialist representation, and it protects the barrister" + RSQ + "s independence " + EMD + " the advocate is not identified with the client" + RSQ + "s cause, which in turn supports the profession" + RSQ + "s paramount duty to the court. It is part of the " + dq("Grand Bargain") + ": in exchange for monopoly, status and self-regulation, the profession accepts duties to the court and the public ahead of its own preferences.\n\nThe rule is not absolute. A barrister may " + EMD + " indeed must " + EMD + " decline a brief where an exception applies, such as a conflict of interest or an inadequate fee. Within those limits, personal distaste for the client, the crime or the politics of the matter is no answer to a brief.\n\nExam angle: link the rule to the solicitor" + "\u2013" + "barrister division, the paramount duty to the court, and the fitness cases (Clyne; Cummins) that police the ethical standards on which the Bargain depends.",
        },
    ],
    10: [
        {
            "qnum": "Q42",
            "question": "What are reserve powers, and to what extent are they constrained by convention?",
            "answer": "Answer. Reserve powers are the non-statutory discretionary powers of the Governor-General (federally) and State Governors: commissioning or dismissing a Prime Minister or Premier, granting or refusing a dissolution of Parliament, and prorogation. They exist alongside the Crown" + RSQ + "s ordinary functions, which are exercised on ministerial advice " + EMD + " the G-G is appointed on the PM" + RSQ + "s advice (s 2) and the King acts on advice.\n\nThey are constrained almost entirely by constitutional convention rather than enforceable law: the Governor-General acts on advice; the government must hold the confidence of the lower house; and supply must be secured. Those conventions are real but uncodified, and their boundaries are contested.\n\nThe 1975 dismissal illustrates the contest. G-G Sir John Kerr dismissed PM Whitlam after the Senate blocked supply. For the dismissal: a PM who cannot secure supply must call an election or resign. Against it: Whitlam held the confidence of the House of Representatives, the chamber that conventionally determines who governs. The episode shows that constitutional crises shape the conventions without codifying them " + EMD + " later practice adjusts, but no court will enforce the limits.\n\nThe same reserve powers and conventions are mirrored at State level (the Governor, appointed on the Premier" + RSQ + "s advice under the Australia Act 1986 (Imp) s 7, acting with the Executive Council). In an essay, engage both sides: reserve powers as a constitutional safety valve versus their tension with representative and responsible government.",
        },
        {
            "qnum": "Q43",
            "question": "How has the Engineers" + RSQ + " Case influenced the High Court" + RSQ + "s approach to constitutional interpretation?",
            "answer": "Answer. Amalgamated Society of Engineers v Adelaide Steamship Co Ltd (1920) 28 CLR 129 revolutionised Australian constitutional interpretation. Before 1920 the Court read Commonwealth powers narrowly, guided by the implied doctrines of reserved State powers and reciprocal immunities of instrumentalities. Engineers swept both away: the Constitution is to be read by its plain words, in their natural meaning and in context, like any other statute " + EMD + " without implications drawn from the federal balance. Barwick later captured the method extrajudicially: you decide on the Commonwealth power without " + dq("looking over your shoulder") + " at the effect on State power.\n\nThe consequences were centralising. The First Uniform Tax Case (1942) let the Commonwealth monopolise income tax through ss 51(ii) and 96, producing vertical fiscal imbalance; the Tasmanian Dam Case (1983) read external affairs to support treaty-implementing legislation on otherwise local matters; WorkChoices (2006) read the corporations power to support national workplace regulation " + EMD + " over dissents from Kirby and Callinan JJ warning of the States" + RSQ + " decline.\n\nTwo qualifications frame the method. The Constitution remains " + dq("broad and general in its terms, intended to apply to varying conditions") + " (Jumbunna Coal Mine (1908) per O" + RSQ + "Connor J), so Commonwealth powers are read generously unless context indicates otherwise. And precedent plays a weaker role in constitutional cases, because only a s 128 referendum can correct judicial error. Engineers" + RSQ + " literalism, tempered by those points, is still the starting point for any constitutional-interpretation answer.",
        },
        {
            "qnum": "Q44",
            "question": "Distinguish representative government from responsible government, with constitutional references.",
            "answer": "Answer. Representative government concerns who makes the laws: the legislature is directly chosen by the people. Sections 7 and 24 require the Senate and the House of Representatives to be " + dq("directly chosen by the people") + ", and s 28 provides for regular elections. The High Court has treated these provisions as a constitutional foundation with doctrinal bite " + EMD + " they ground the implied freedom of political communication (Lange v ABC (1997), tested by structured proportionality under McCloy (2015)) and invalidate disproportionate burdens on the franchise (Roach (2007); Rowe (2010)).\n\nResponsible government concerns who governs and to whom they answer: the executive is accountable to the legislature. Ministers must be, or become, members of Parliament (s 64); the government holds office only while it commands the confidence of the lower house; and ministerial responsibility " + EMD + " collective (Cabinet solidarity for government decisions) and individual (ministers answering for their departments) " + EMD + " channels that accountability, supported by Question Time, estimates hearings, parliamentary committees and the Auditor-General. Responsible government runs on convention rather than the constitutional text " + EMD + " Cabinet itself is not mentioned in the Constitution (Peko-Wallsend (1987)) " + EMD + " and individual responsibility has weakened in modern practice.\n\nThe distinction matters because the two doctrines do different work: representative government legitimises the legislature and limits burdens on political communication and voting, while responsible government disciplines the executive between elections. Australia" + RSQ + "s " + dq("Washminster") + " system fuses the two in practice " + EMD + " ministers sit in, and are drawn from, the elected Parliament.",
        },
    ],
}

# ---------------------------------------------------------------------------
# 5. Topic 15 — Exam-day briefing & lecturer flags (Part A + Part B + E.4)
# ---------------------------------------------------------------------------
TOPIC_15 = {
    "num": 15,
    "title": "Exam-day briefing & lecturer flags",
    "key_concepts": [
        "Format (September 2026, confirmed in the Week 12 lecture): five questions on the paper; answer FOUR; 20 marks each; marked out of 80. 15 minutes reading/planning + ~45 minutes per question (\u2248 3 h 15 min). Only your first four UNcrossed-out answers are marked " + EMD + " a crossed-out attempt does not count, and effort on a fifth question is entirely wasted.",
        "Timing: choose your four questions during reading time and note every sub-part. Write a timing plan on paper and obey it (for a 9:00 start: Q1 9:15, Q2 10:00, Q3 10:45, Q4 11:30, finish 12:15). When a question" + RSQ + "s time is up, move on " + EMD + " it is much harder to push an answer from 16 to 17 than to pick up the first marks of the next question. Expect to write ~1,000 words/hour (~200" + "\u2013" + "250 words per page); leaving a question half-done is the single most common cause of failure.",
        "If caught short mid-answer: switch to dot points setting out where the answer was going " + EMD + " the cases, legislation and issues you would have dealt with " + EMD + " leave a couple of pages, write " + dq("PTO") + ", and come back at the end if time allows.",
        "What the examiner rewards (March 2026 Examiner" + RSQ + "s Comments): a clear thesis introduced up front; critical engagement with the actual question " + EMD + " including rejecting a provocative proposition and arguing a substantiated counter-position; every component of multi-pronged questions answered; several accurate authorities from the course materials; red herrings identified and dismissed; full sentences and paragraphs " + EMD + " never pure point form.",
        "What gets penalised: reproducing prepared notes uncritically (over-reliance on the open-book format); copying word-for-word without acknowledgment; conclusions asserted without reasoned analysis or authority; citing no provision or case on point; misstating what cases stand for; conflating the approaches to statutory interpretation; irrelevant material; unanswered question-parts.",
        "Open-book discipline: a pile of notes " + dq("will do you no good") + " " + EMD + " distil your material so you can marshal it; use the pack to locate authority fast, then answer the precise question asked. Coverage insurance: the lecturer cannot cover everything " + EMD + " have at least one or two sentences on each item in every topic. Keep 5 minutes per question to re-read your answer against the question asked (kill regurgitation).",
        "Citation: formal AGLC4 is NOT required in the exam " + EMD + " but do identify the legislation (name + section) and the case (name + year). Underline case names and legislation so the marker can see where to look on the page, and write as clearly as you possibly can.",
        "Problem questions: the representation in the facts will be deliberately vague " + EMD + " argue whether it suffices and map both branches (" + dq("maybe, maybe not " + EMD + " if, if not") + "). Always check defined terms (e.g. " + dq("person") + ") in the relevant interpretation Act (" + dq("in the examination you would 100% go back and talk about person") + "). Identify the correct client, the correct entity to sue, and the correct court before advising.",
        "Lecturer" + RSQ + "s must-know flags (Parts B): Blackstone, Commentaries on the Laws of England (1765" + "\u2013" + "69); the Judicature Acts 1873" + "\u2013" + "75; the four schools of jurisprudence (characterise each); context and purpose considered at the first stage (CIC Insurance; SZTAL); the division of powers (ss 51, 52, 90, 107, 109); separation of powers (" + dq("learn it properly and regurgitate it") + "); s 75(v) mandamus/prohibition; the reception date (25 July 1828); the Australia Act 1986 ended Privy Council appeals (" + dq("I" + RSQ + "ve said it 3 times") + "); the maxims of equity; " + dq("plenary power") + " (s 5 Constitution Act 1902 (NSW)) " + EMD + " " + dq("a particular favourite of examiners the country over") + "; merits review vs judicial review; Boilermakers; the Kable ingredients (independence/impartiality, procedural fairness, open justice, the duty to give reasons).",
        "Likely September 2026 hotspots: statutory interpretation (every year); precedent/dissent/judicial law-making; native title including Commonwealth v Yunupingu [2025] HCA 6; s 109 inconsistency including Stott v Commonwealth [2025] HCA 39; executive power (Pape; Williams " + EMD + " the new Topic 13 lecture); reserve powers; separation of powers and Kable; what makes a body a " + dq("court") + " and the content of judicial power (Lane v Morrison; Boilermakers; Burns v Corbett); merits review vs judicial review and supervisory jurisdiction (Kirk; Craig; Probuild); ADR; the legal profession and AI; definitional pairs.",
        "NOT needed: the warm-up cases (e.g. Thornton v Shoe Lane Parking " + EMD + " " + dq("you don" + RSQ + "t need to have a summary of Thornton") + "); the Sale of Goods Act (" + dq("don" + RSQ + "t write that in your exam") + "); Wikipedia (" + dq("don" + RSQ + "t quote Wikipedia in exams or assignments") + ").",
        "Answer structure per question: one-sentence thesis up front \u2192 issue-by-issue analysis with case/section authority \u2192 counter-argument \u2192 conclusion. For definitional pairs: synthesise similarities and differences, and always end with one sentence on why the distinction matters.",
        "Logistics: the exam is held in the city, not on campus " + EMD + " confirm exactly where the room is, plan parking/transport, and go and look at the room before exam day. Bring an annotated copy of the Constitution " + EMD + " you will have to refer to it. Print the pack double-sided and tab Parts A" + "\u2013" + "E for the fastest access.",
    ],
    "questions": [],
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    with open(PATH, encoding="utf-8") as f:
        data = json.load(f)

    topics = {t["num"]: t for t in data["topics"]}
    assert len(topics) == 14, "expected 14 topics"

    # repairs (truncated strings -> full text)
    for (num, idx), (prefix, new) in sorted(REPAIRS.items()):
        old = topics[num]["key_concepts"][idx]
        assert old.startswith(prefix.rstrip()), "prefix mismatch at topic %d C%d: %r" % (num, idx, old[:60])
        assert old.rstrip().endswith("..."), "expected truncated string at topic %d C%d" % (num, idx)
        topics[num]["key_concepts"][idx] = new

    # rewrites (exact replacements of complete strings)
    for (num, idx), (old_text, new) in sorted(REWRITES.items()):
        old = topics[num]["key_concepts"][idx]
        assert old == old_text, "rewrite mismatch at topic %d C%d: %r" % (num, idx, old[:80])
        topics[num]["key_concepts"][idx] = new

    # additions (dedupe by first 60 chars)
    for num, new_concepts in sorted(ADDITIONS.items()):
        existing = topics[num]["key_concepts"]
        for c in new_concepts:
            key = c[:60]
            if any(e[:60] == key for e in existing):
                print("SKIP duplicate concept in topic", num, key)
                continue
            existing.append(c)

    # new questions (dedupe by qnum and by question prefix)
    existing_qnums = {q["qnum"] for t in data["topics"] for q in t["questions"]}
    for num, qs in sorted(NEW_QUESTIONS.items()):
        for q in qs:
            assert q["qnum"] not in existing_qnums, "qnum clash: " + q["qnum"]
            if any(ex["question"][:60] == q["question"][:60] for t in data["topics"] for ex in t["questions"]):
                print("SKIP duplicate question", q["qnum"])
                continue
            topics[num]["questions"].append(q)
            existing_qnums.add(q["qnum"])

    # topic 15
    assert 15 not in topics
    data["topics"].append(TOPIC_15)

    with open(PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    total_q = sum(len(t["questions"]) for t in data["topics"])
    print("OK: topics=%d questions=%d" % (len(data["topics"]), total_q))
    for t in data["topics"]:
        print("  topic %2d: %2d concepts, %d questions" % (t["num"], len(t["key_concepts"]), len(t["questions"])))


if __name__ == "__main__":
    sys.exit(main())
